//go:build !skip_blueprinter

// Code generated by blueprinter. DO NOT EDIT.

package container

import (
	github_com_yuemori_blueprinter_example_app1_handler "github.com/yuemori/blueprinter/example/app1/handler"
	github_com_yuemori_blueprinter_example_app1_repository "github.com/yuemori/blueprinter/example/app1/repository"
)

// github.com/yuemori/blueprinter/example/app1/handler
func (f *Container) ResolveNewLoginHandler() *github_com_yuemori_blueprinter_example_app1_handler.LoginHandler {
	return github_com_yuemori_blueprinter_example_app1_handler.NewLoginHandler(
		// github.com/yuemori/blueprinter/example/app1/handler.UserRepository
		f.github_com_yuemori_blueprinter_example_app1_handler_UserRepository(),
	)
}

func (f *Container) ResolveNewSignupHandler() *github_com_yuemori_blueprinter_example_app1_handler.SignupHandler {
	return github_com_yuemori_blueprinter_example_app1_handler.NewSignupHandler(
		// github.com/yuemori/blueprinter/example/app1/handler.UserRepository
		f.github_com_yuemori_blueprinter_example_app1_handler_UserRepository(),
	)
}
// github.com/yuemori/blueprinter/example/app1/repository
func (f *Container) ResolveNewUserRepository() *github_com_yuemori_blueprinter_example_app1_repository.UserRepository {
	return github_com_yuemori_blueprinter_example_app1_repository.NewUserRepository(
		// *database/sql.DB
		f.db,
		// *log.Logger
		f.logger,
	)
}

// github.com/yuemori/blueprinter/example/app1/handler
func (f *Container) github_com_yuemori_blueprinter_example_app1_handler_UserRepository() github_com_yuemori_blueprinter_example_app1_handler.UserRepository {
	return github_com_yuemori_blueprinter_example_app1_repository.NewUserRepository(
		// *database/sql.DB
		f.db,
		// *log.Logger
		f.logger,
	)
}

